[package]
name = "sphere-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
find_folder = "0.3.0"
itertools = "0.13.0"
nalgebra = "0.33.0"
piston_window = "0.132.0"
rand = "0.8.5"
types = "0.1.2"
vector2 = "0.1.5"
